
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import { Workflow, MessageSquare, Zap, Brain } from "lucide-react";

export const NextGenWorkflowsTab = () => {
  const workflowMetrics = {
    naturalLanguageWorkflows: 156,
    autoGeneratedProcesses: 89,
    workflowIntelligence: 95.3,
    adaptationRate: 87.2
  };

  const nlWorkflows = [
    { name: "Patient discharge process when bed availability drops below 80%", confidence: 94, status: "active" },
    { name: "Emergency alert routing based on severity and staff availability", confidence: 89, status: "optimizing" },
    { name: "Lab result distribution prioritizing critical values", confidence: 97, status: "active" },
    { name: "Insurance verification workflow with automated follow-up", confidence: 92, status: "learning" }
  ];

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'active': return 'bg-green-500/10 text-green-600 border-green-500/20';
      case 'optimizing': return 'bg-blue-500/10 text-blue-600 border-blue-500/20';
      case 'learning': return 'bg-purple-500/10 text-purple-600 border-purple-500/20';
      default: return 'bg-gray-500/10 text-gray-600 border-gray-500/20';
    }
  };

  return (
    <Card className="bg-card/80 border-border backdrop-blur-sm">
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <Workflow className="h-5 w-5 text-purple-400" />
          Next-Generation Workflow Intelligence
        </CardTitle>
        <CardDescription>
          Natural language workflow creation with AI-powered optimization and adaptation
        </CardDescription>
      </CardHeader>
      <CardContent>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">
          <div className="p-4 bg-purple-500/10 rounded-lg border border-purple-500/20">
            <div className="text-2xl font-bold text-purple-400">{workflowMetrics.naturalLanguageWorkflows}</div>
            <div className="text-xs text-muted-foreground">NL Workflows</div>
          </div>
          <div className="p-4 bg-blue-500/10 rounded-lg border border-blue-500/20">
            <div className="text-2xl font-bold text-blue-400">{workflowMetrics.autoGeneratedProcesses}</div>
            <div className="text-xs text-muted-foreground">Auto-Generated</div>
          </div>
          <div className="p-4 bg-green-500/10 rounded-lg border border-green-500/20">
            <div className="text-2xl font-bold text-green-400">{workflowMetrics.workflowIntelligence}%</div>
            <div className="text-xs text-muted-foreground">Intelligence Score</div>
          </div>
          <div className="p-4 bg-orange-500/10 rounded-lg border border-orange-500/20">
            <div className="text-2xl font-bold text-orange-400">{workflowMetrics.adaptationRate}%</div>
            <div className="text-xs text-muted-foreground">Adaptation Rate</div>
          </div>
        </div>

        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <h4 className="font-semibold text-foreground">Natural Language Workflows</h4>
            <Button variant="outline" size="sm">
              <MessageSquare className="h-4 w-4 mr-2" />
              Create Workflow
            </Button>
          </div>
          
          {nlWorkflows.map((workflow, index) => (
            <div key={index} className="p-4 border border-border rounded-lg">
              <div className="flex items-center justify-between mb-3">
                <div className="flex items-center gap-2">
                  <Brain className="h-4 w-4 text-purple-400" />
                  <span className="font-medium text-sm">{workflow.name}</span>
                </div>
                <Badge variant="outline" className={getStatusColor(workflow.status)}>
                  {workflow.status}
                </Badge>
              </div>
              <div className="flex items-center justify-between mb-2">
                <span className="text-sm text-muted-foreground">Confidence Level</span>
                <span className="font-medium">{workflow.confidence}%</span>
              </div>
              <Progress value={workflow.confidence} className="h-2" />
            </div>
          ))}
        </div>

        <div className="mt-6 p-4 bg-gradient-to-r from-purple-500/10 to-pink-500/10 rounded-lg border border-purple-500/20">
          <h4 className="font-semibold text-foreground mb-2">Next-Gen Workflow Features</h4>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-3 text-sm">
            <div className="flex items-center gap-2">
              <Zap className="h-4 w-4 text-purple-400" />
              <span>Natural language workflow creation</span>
            </div>
            <div className="flex items-center gap-2">
              <Zap className="h-4 w-4 text-purple-400" />
              <span>Intelligent process optimization</span>
            </div>
            <div className="flex items-center gap-2">
              <Zap className="h-4 w-4 text-purple-400" />
              <span>Adaptive workflow evolution</span>
            </div>
            <div className="flex items-center gap-2">
              <Zap className="h-4 w-4 text-purple-400" />
              <span>Context-aware automation</span>
            </div>
          </div>
        </div>
      </CardContent>
    </Card>
  );
};
