
-- Clear all data from hospital operational tables
TRUNCATE TABLE workflow_executions RESTART IDENTITY CASCADE;
TRUNCATE TABLE automation_rules RESTART IDENTITY CASCADE;
TRUNCATE TABLE ml_models RESTART IDENTITY CASCADE;
TRUNCATE TABLE ml_training_jobs RESTART IDENTITY CASCADE;
TRUNCATE TABLE surge_predictions RESTART IDENTITY CASCADE;
TRUNCATE TABLE data_sources RESTART IDENTITY CASCADE;
TRUNCATE TABLE data_pipelines RESTART IDENTITY CASCADE;
TRUNCATE TABLE data_quality_scores RESTART IDENTITY CASCADE;
TRUNCATE TABLE vision_tasks RESTART IDENTITY CASCADE;
TRUNCATE TABLE knowledge_graph_nodes RESTART IDENTITY CASCADE;
TRUNCATE TABLE alerts RESTART IDENTITY CASCADE;
TRUNCATE TABLE beds RESTART IDENTITY CASCADE;
TRUNCATE TABLE departments RESTART IDENTITY CASCADE;
TRUNCATE TABLE equipment RESTART IDENTITY CASCADE;
TRUNCATE TABLE patients RESTART IDENTITY CASCADE;
TRUNCATE TABLE patient_visits RESTART IDENTITY CASCADE;
TRUNCATE TABLE patient_surveys RESTART IDENTITY CASCADE;
TRUNCATE TABLE medication_safety_alerts RESTART IDENTITY CASCADE;
TRUNCATE TABLE staff_schedules RESTART IDENTITY CASCADE;
TRUNCATE TABLE budget_allocations RESTART IDENTITY CASCADE;
TRUNCATE TABLE billing_transactions RESTART IDENTITY CASCADE;
TRUNCATE TABLE insurance_claims RESTART IDENTITY CASCADE;
TRUNCATE TABLE claim_denials RESTART IDENTITY CASCADE;
TRUNCATE TABLE wait_times RESTART IDENTITY CASCADE;
TRUNCATE TABLE sla_configurations RESTART IDENTITY CASCADE;
TRUNCATE TABLE slas RESTART IDENTITY CASCADE;
TRUNCATE TABLE kpis RESTART IDENTITY CASCADE;
TRUNCATE TABLE metrics_snapshots RESTART IDENTITY CASCADE;
TRUNCATE TABLE quality_indicators RESTART IDENTITY CASCADE;
TRUNCATE TABLE quality_measurements RESTART IDENTITY CASCADE;
TRUNCATE TABLE quality_improvement_initiatives RESTART IDENTITY CASCADE;
TRUNCATE TABLE compliance_areas RESTART IDENTITY CASCADE;
TRUNCATE TABLE risk_assessments RESTART IDENTITY CASCADE;
TRUNCATE TABLE accreditations RESTART IDENTITY CASCADE;
TRUNCATE TABLE notification_channels RESTART IDENTITY CASCADE;
TRUNCATE TABLE daily_summaries RESTART IDENTITY CASCADE;
TRUNCATE TABLE audit_logs RESTART IDENTITY CASCADE;
TRUNCATE TABLE permissions RESTART IDENTITY CASCADE;
TRUNCATE TABLE pipeline_executions RESTART IDENTITY CASCADE;
TRUNCATE TABLE capacity_forecasts RESTART IDENTITY CASCADE;
TRUNCATE TABLE patient_flow_events RESTART IDENTITY CASCADE;
TRUNCATE TABLE bed_status_history RESTART IDENTITY CASCADE;
TRUNCATE TABLE integrations RESTART IDENTITY CASCADE;
TRUNCATE TABLE widgets RESTART IDENTITY CASCADE;
TRUNCATE TABLE report_executions RESTART IDENTITY CASCADE;
TRUNCATE TABLE user_roles RESTART IDENTITY CASCADE;
TRUNCATE TABLE alert_subscriptions RESTART IDENTITY CASCADE;
TRUNCATE TABLE api_keys RESTART IDENTITY CASCADE;
TRUNCATE TABLE rule_executions RESTART IDENTITY CASCADE;
TRUNCATE TABLE workflows RESTART IDENTITY CASCADE;

-- Note: We're not truncating the profiles table to preserve user profile data
-- and auth-related tables are managed by Supabase
