
-- Phase 4 & 6: Remove all clinical tables and clear all data from remaining tables

-- Drop clinical-related tables
DROP TABLE IF EXISTS allergies CASCADE;
DROP TABLE IF EXISTS careplans CASCADE;
DROP TABLE IF EXISTS conditions CASCADE;
DROP TABLE IF EXISTS devices CASCADE;
DROP TABLE IF EXISTS encounters CASCADE;
DROP TABLE IF EXISTS patients CASCADE;
DROP TABLE IF EXISTS patient_visits CASCADE;
DROP TABLE IF EXISTS patient_education_log CASCADE;
DROP TABLE IF EXISTS patient_surveys CASCADE;
DROP TABLE IF EXISTS medication_adherence_log CASCADE;
DROP TABLE IF EXISTS medication_safety_alerts CASCADE;
DROP TABLE IF EXISTS surgical_outcomes CASCADE;
DROP TABLE IF EXISTS lab_tests CASCADE;
DROP TABLE IF EXISTS lab_test_types CASCADE;
DROP TABLE IF EXISTS critical_lab_values CASCADE;
DROP TABLE IF EXISTS care_pathway_analytics CASCADE;
DROP TABLE IF EXISTS protocol_adherence_metrics CASCADE;
DROP TABLE IF EXISTS predictive_diagnostic_suggestions CASCADE;
DROP TABLE IF EXISTS education_materials CASCADE;

-- Clear all data from remaining operational tables
TRUNCATE TABLE workflow_executions RESTART IDENTITY CASCADE;
TRUNCATE TABLE automation_rules RESTART IDENTITY CASCADE;
TRUNCATE TABLE ml_models RESTART IDENTITY CASCADE;
TRUNCATE TABLE ml_training_jobs RESTART IDENTITY CASCADE;
TRUNCATE TABLE surge_predictions RESTART IDENTITY CASCADE;
TRUNCATE TABLE data_sources RESTART IDENTITY CASCADE;
TRUNCATE TABLE data_pipelines RESTART IDENTITY CASCADE;
TRUNCATE TABLE data_quality_scores RESTART IDENTITY CASCADE;
TRUNCATE TABLE vision_tasks RESTART IDENTITY CASCADE;
TRUNCATE TABLE alerts RESTART IDENTITY CASCADE;
TRUNCATE TABLE beds RESTART IDENTITY CASCADE;
TRUNCATE TABLE departments RESTART IDENTITY CASCADE;
TRUNCATE TABLE equipment RESTART IDENTITY CASCADE;
TRUNCATE TABLE staff_schedules RESTART IDENTITY CASCADE;
TRUNCATE TABLE budget_allocations RESTART IDENTITY CASCADE;
TRUNCATE TABLE billing_transactions RESTART IDENTITY CASCADE;
TRUNCATE TABLE insurance_claims RESTART IDENTITY CASCADE;
TRUNCATE TABLE claim_denials RESTART IDENTITY CASCADE;
TRUNCATE TABLE wait_times RESTART IDENTITY CASCADE;
TRUNCATE TABLE sla_configurations RESTART IDENTITY CASCADE;
TRUNCATE TABLE slas RESTART IDENTITY CASCADE;
TRUNCATE TABLE kpis RESTART IDENTITY CASCADE;
TRUNCATE TABLE metrics_snapshots RESTART IDENTITY CASCADE;
TRUNCATE TABLE quality_indicators RESTART IDENTITY CASCADE;
TRUNCATE TABLE quality_measurements RESTART IDENTITY CASCADE;
TRUNCATE TABLE quality_improvement_initiatives RESTART IDENTITY CASCADE;
TRUNCATE TABLE compliance_areas RESTART IDENTITY CASCADE;
TRUNCATE TABLE risk_assessments RESTART IDENTITY CASCADE;
TRUNCATE TABLE accreditations RESTART IDENTITY CASCADE;
TRUNCATE TABLE notification_channels RESTART IDENTITY CASCADE;
TRUNCATE TABLE daily_summaries RESTART IDENTITY CASCADE;
TRUNCATE TABLE audit_logs RESTART IDENTITY CASCADE;
TRUNCATE TABLE permissions RESTART IDENTITY CASCADE;
